version: '3.8'

services:
  db:
    image: mongo
    container_name: "mongo"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    logging:
      driver: none
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "server"
    restart: always
    ports:
      - 4000:4000
    command: yarn runServer
    depends_on:
      - db
volumes:
  mongo_server:
